OOP school library: add Person, Student and Teacher classes
Fombi-Favour/school-library-rb pull request #1
Opened 2023-11-07 15:29 UTC by Fombi-Favour

In this activity, we:
- setup the environment
- created class files for `Person`, `Student` and `Teacher`
- added constructors and methods for each file
- updated the readme file

2023-11-07 16:36 UTC, Omar-Muhamad requested changes
# Changes Required ♻️
### Hi @Fombi-Favour,

### Nice job, you are almost there.

![cat-driving-serious](https://user-images.githubusercontent.com/68796232/223284600-852bcd90-1495-4a40-8515-cc12636b369b.gif)

## (Highlights) Good Points: :+1:
- Your work is well documented. ✔
- The correct workflow is used.  ✔
- All linters checks are ok. ✔

## (Changes Required) Aspects to improve: ♻️

- [ ] Please check the inline comments below ⬇️.

## [Optional] suggestions:

- Nothing to mention.

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-11-07 16:36 UTC, Omar-Muhamad commented on person.rb
> +    @id = id
- [ ] As per this [requirement](https://github.com/microverseinc/curriculum-ruby/blob/main/oop/school_library_people.md#:~:text=parent_permission%20as%20parameter.-,name%20and%20parent_permission%20are%20optional%20and%20have%20default%20values%20of%20%22Unknown%22%20and%20true.,-Getters%20for%20%40id), The `parent_permission` parameter has a default value `true`. Please add it.

- [ ] [Optional] [Highly recommended] It's a good practice and professional to generate the `id` automatically like the suggestion below, not as a parameter as you did here.
```ruby
def initialize(age, name = "Unknown", parent_permission = true)
    @id = Random.rand(1..1000)
    @age = age
    @name = name
    @parent_permission = parent_permission
  end
```

2023-11-07 16:36 UTC, Omar-Muhamad commented on student.rb
> +    super(id, name, age, parent_permision)
- [ ] As per this [requirement](https://github.com/microverseinc/curriculum-ruby/blob/main/oop/school_library_people.md#:~:text=parent_permission%20as%20parameter.-,name%20and%20parent_permission%20are%20optional%20and%20have%20default%20values%20of%20%22Unknown%22%20and%20true.,-Getters%20for%20%40id), The `parent_permission` parameter has a default value `true`. Please add it.

- [ ] [Optional] [Highly recommended] If you implement the `id` suggestion above, please remove the `id` from lines 4 and 5.

[Hint] It should be like that after fixing:
```ruby
def initialize(age, classroom, name = "Unknown", parent_permission = true)  
    super(age, name, parent_permission)
    @classroom = classroom
  end
```

2023-11-07 16:36 UTC, Omar-Muhamad commented on teacher.rb
> +    super(id, name, age, parent_permision)
- [ ] As per this [requirement](https://github.com/microverseinc/curriculum-ruby/blob/main/oop/school_library_people.md#:~:text=parent_permission%20as%20parameter.-,name%20and%20parent_permission%20are%20optional%20and%20have%20default%20values%20of%20%22Unknown%22%20and%20true.,-Getters%20for%20%40id), The `parent_permission` parameter has a default value `true`. Please add it.

2023-11-07 16:41 UTC, Fombi-Favour commented on person.rb
> +    @id = id
I followed the requirement by adding the default value of the parent_permission for all the files. But it gives me a linter error. That's why I removed it and left it without a default value

2023-11-07 16:45 UTC, Omar-Muhamad commented on person.rb
> +    @id = id
Hi @Fombi-Favour,
try `parent_permission: true` instead of `parent_permission = true`

2023-11-07 16:59 UTC, Omar-Muhamad approved these changes
# Approved ✔
### Hi @Fombi-Favour,
#### Great job, Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 

### Congratulations! 🎉 
### ⚠️Please consider the Optional suggestions below⚠️

![robert-redford-nod](https://user-images.githubusercontent.com/68796232/223284088-e0a9d61f-2bb6-4af2-96e8-1e78bb532567.gif)

## (Highlights) Good Points: :+1:
- Your work is well documented. ✔
- The correct workflow is used.  ✔
- All linters checks are ok. ✔

## (Changes Required) Aspects to improve: ♻️

- N/A

## [Optional] suggestions:

- Please check the inline comments below ⬇.

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-11-07 16:59 UTC, Omar-Muhamad commented on person.rb
> +    @id = id
- [ ] [Optional] [Highly recommended] It's a good practice and professional to generate the `id` automatically like the suggestion below, not as a parameter as you did here.
```ruby
def initialize(age, name = "Unknown", parent_permission: true)
    @id = Random.rand(1..1000)
    @age = age
```

2023-11-07 16:59 UTC, omar-muhamad commented on student.rb
> +    super(id, name, age, parent_permision)
- [ ] [Optional] [Highly recommended] If you implement the `id` suggestion above, please remove the `id` from lines 4 and 5.

2023-11-07 16:59 UTC, Omar-Muhamad commented on teacher.rb
> +    super(id, name, age, parent_permision)
- [ ] [Optional] [Highly recommended] Same here, If you implement the `id` suggestion above, please remove the `id` from lines 4 and 5.

2023-11-07 17:01 UTC, merged

2023-12-04 09:54 UTC, danmainah commented
Hi @Fombi-Favour , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 🎉 🎉 

## Highlights
✔️  Implemented the project requirements.
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._